<script setup lang="ts">
import type { GuestRequestCategory, GuestSpecialRequest, GuestSpecialRequestsResponse } from '~~/shared/types/backend'

const props = defineProps<{ bookingId: string, enabled: boolean }>()
const items = ref<GuestSpecialRequest[]>([]); const state = ref<'idle' | 'loading' | 'ready' | 'disabled' | 'error'>('idle'); const error = ref(''); const submitting = ref(false); let generation = 0
const isApi = computed(() => useRuntimeConfig().public.bookingMode === 'api')
const form = reactive({ category: 'other' as GuestRequestCategory, description: '', targetTime: '' })
const categories: Record<GuestRequestCategory, string> = { early_arrival: 'Datang lebih awal', late_departure: 'Keluar lebih lambat', high_floor: 'Lantai tinggi', quiet_room: 'Kamar tenang', bed_type: 'Tipe tempat tidur', celebration_setup: 'Persiapan perayaan', baby_crib: 'Tempat tidur bayi', dietary_allergy: 'Alergi/kebutuhan makanan', other: 'Lainnya' }
const statusLabel: Record<string, string> = { pending: 'Menunggu', acknowledged: 'Diterima staf', fulfilled: 'Selesai', declined: 'Tidak dapat dipenuhi' }
const loading = computed(() => state.value === 'loading')
const { showIndicator, isSlow } = usePendingFeedback(loading)
function message(cause: unknown) { const v = cause as { statusCode?: number, statusMessage?: string, data?: { statusMessage?: string, data?: { code?: string } } }; return { status: v.statusCode, code: v.data?.data?.code, text: v.data?.statusMessage || v.statusMessage || 'Permintaan belum dapat dimuat.' } }
async function load() {
  if (!isApi.value) { state.value = 'ready'; return }
  const current = ++generation; state.value = 'loading'; error.value = ''; try { const response = await $fetch<GuestSpecialRequestsResponse>(`/api/bff/guest/bookings/${encodeURIComponent(props.bookingId)}/special-requests`); if (current !== generation) return; items.value = response.requests; state.value = 'ready' }
  catch (cause) { if (current !== generation) return; const failure = message(cause); state.value = failure.code === 'FEATURE_DISABLED' || failure.status === 404 || failure.status === 501 ? 'disabled' : 'error'; error.value = failure.text }
}
async function submit() {
  if (submitting.value) return; submitting.value = true; error.value = ''; try { if (isApi.value) await $fetch(`/api/bff/guest/bookings/${encodeURIComponent(props.bookingId)}/special-requests`, { method: 'POST', headers: { 'X-Pulang-CSRF': '1' }, body: { category: form.category, description: form.description, target_time: form.targetTime } }); else items.value.unshift({ id: `sample-${Date.now()}`, booking_id: props.bookingId, category: form.category, department: 'front_desk', description: form.description, target_time: form.targetTime || undefined, status: 'pending', created_at: new Date().toISOString(), updated_at: new Date().toISOString() }); form.description = ''; form.targetTime = ''; await load() }
  catch (cause) { error.value = message(cause).text }
  finally { submitting.value = false }
}
onMounted(() => { if (props.enabled) load(); else state.value = 'disabled' }); onBeforeUnmount(() => generation++)
</script>

<template><section class="panel stack" aria-labelledby="request-title"><h2 id="request-title">Permintaan khusus</h2><UiInlineAlert v-if="!isApi" tone="info">Mode demo: permintaan tersimpan pada halaman ini saja dan tidak dikirim ke hotel.</UiInlineAlert><UiInlineAlert v-if="state === 'disabled'" tone="info">Permintaan baru belum tersedia untuk booking ini. Hubungi hotel bila memerlukan bantuan.</UiInlineAlert><div v-else-if="state === 'loading'" class="request-loading" role="status"><UiLoadingIndicator v-if="showIndicator" size="small" /><span>{{ isSlow ? 'Permintaan masih sedang dimuat…' : 'Memuat permintaan…' }}</span></div><UiInlineAlert v-else-if="state === 'error'" tone="error" live>{{ error }} <button class="text-action" type="button" @click="load">Coba lagi</button></UiInlineAlert><template v-if="state === 'ready'"><p v-if="!items.length" class="muted">Belum ada permintaan khusus.</p><article v-for="item in items" :key="item.id" class="request-row"><div><strong>{{ categories[item.category] || item.category }}</strong><span class="badge">{{ statusLabel[item.status] || item.status }}</span></div><p>{{ item.description }}</p><p v-if="item.staff_notes" class="muted">Catatan hotel: {{ item.staff_notes }}</p></article><form class="stack" @submit.prevent="submit"><div class="field"><label for="request-category">Jenis permintaan</label><select id="request-category" v-model="form.category" :disabled="submitting"><option v-for="(label, value) in categories" :key="value" :value="value">{{ label }}</option></select></div><div class="field"><label for="request-description">Detail permintaan</label><textarea id="request-description" v-model="form.description" maxlength="1000" rows="4" required :disabled="submitting" /></div><div class="field"><label for="request-time">Waktu target (opsional)</label><input id="request-time" v-model="form.targetTime" type="time" :disabled="submitting" /></div><UiInlineAlert tone="info">Permintaan akan diperiksa hotel dan belum berarti disetujui. Perubahan tanggal atau pembatalan memakai proses terpisah.</UiInlineAlert><BrandButton type="submit" :loading="submitting" loading-label="Mengirim…" slow-loading-label="Masih mengirim…">Kirim permintaan</BrandButton></form></template></section></template>
<style scoped>.request-loading { min-height: 44px; display: flex; align-items: center; gap: 10px; color: var(--muted); font-weight: 800; }.request-row { display: grid; gap: 8px; padding: 14px 0; border-bottom: 1px solid var(--line); }.request-row div { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 8px; }.request-row p { margin: 0; }.text-action { min-height: 0; border: 0; background: transparent; color: inherit; text-decoration: underline; font-weight: 800; }</style>
