import { expect, test } from '@playwright/test'

test('redirects the root directly to the booking webapp', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/\/booking$/)
  await expect(page.getByRole('heading', { name: 'Temukan ruang untuk pulang.' })).toBeVisible()
})

test('navigates a complete single-room demo flow', async ({ page }) => {
  await page.goto('/booking')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await page.getByRole('button', { name: 'Cari kamar' }).click()
  await expect(page.getByRole('heading', { name: 'Pilih cara Anda pulang.' })).toBeVisible()
  const firstCard = page.locator('.room-card').first()
  await firstCard.getByLabel('Varian / tempat tidur').selectOption('deluxe-king-bay')
  await firstCard.getByLabel('Room Only').check()
  await firstCard.getByRole('button', { name: 'Pilih kamar & paket' }).click()
  await page.getByRole('button', { name: 'Lanjut' }).click()
  await page.getByLabel('Nama lengkap').fill('Tamu Demo')
  await page.getByLabel('Email').fill('demo@example.test')
  await page.getByRole('button', { name: 'Tinjau booking' }).click()
  await page.getByLabel(/Saya telah membaca/).check()
  await page.getByLabel(/Saya menyetujui pemrosesan data/).check()
  await page.getByRole('button', { name: 'Simulasikan booking' }).click()
  await expect(page.getByRole('heading', { name: 'Menunggu pembayaran' })).toBeVisible()
  await page.getByRole('button', { name: 'Batalkan booking' }).click()
  const dialog = page.getByRole('dialog', { name: 'Batalkan booking?' })
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'Batalkan booking' }).click()
  await dialog.getByRole('button', { name: 'Ya, batalkan booking' }).click()
  await expect(page.getByRole('heading', { name: 'Dibatalkan' })).toBeVisible()
  await expect(page.getByText('Booking telah dibatalkan. Status refund diperiksa terpisah.')).toBeVisible()
})

test('restores search from the URL and rejects invalid query', async ({ page }) => {
  await page.goto('/booking/results?v=1&check_in=2026-10-03&check_out=2026-10-04&guests=2:7')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await expect(page.getByRole('heading', { name: 'Kamar dan paket' })).toBeVisible()
  await page.goto('/booking/results?check_in=nope')
  await expect(page.getByText(/URL pencarian tidak valid/)).toBeVisible()
})

test('offers explicit sample staff workspaces while API staff routes stay locked', async ({ page, request }) => {
  await page.goto('/staff/housekeeping')
  await expect(page.getByText('Preview data sample')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Housekeeping board.' })).toBeVisible()
  await expect(page.getByText('6 kamar pada hasil filter.')).toBeVisible()
  await page.goto('/staff/front-desk')
  await expect(page.getByRole('heading', { name: 'Front desk.' })).toBeVisible()
  await page.goto('/staff/finance')
  await expect(page.getByRole('heading', { name: 'Finance.' })).toBeVisible()
  const response = await request.get('/api/bff/staff/housekeeping/rooms')
  expect(response.status()).toBe(503)
  expect(await response.json()).toMatchObject({ data: { code: 'CAPABILITY_DISABLED' } })
  const mutation = await request.post('/api/bff/staff/finance/refunds', { headers: { 'X-Pulang-CSRF': '1' }, data: { booking_id: 'demo', amount_minor: 1, reason: 'sample' } })
  expect(mutation.status()).toBe(503)
  const guestRequest = await request.get('/api/bff/guest/bookings/demo/special-requests')
  expect(guestRequest.status()).toBe(503)
})

test('runs housekeeping and handover sample actions without backend writes', async ({ page }) => {
  await page.goto('/staff/housekeeping')
  await page.getByRole('button', { name: 'Ubah status' }).first().click()
  await page.getByRole('button', { name: 'Simpan simulasi', exact: true }).click()
  await expect(page.getByText(/Simulasi status kamar/)).toBeVisible()
  await page.goto('/staff/front-desk/handover')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await page.getByLabel('Masalah pending').fill('Periksa kedatangan malam.')
  await page.getByRole('button', { name: 'Simpan catatan sample' }).click()
  await expect(page.getByText('Catatan sample ditambahkan.')).toBeVisible()
})

test('runs stay and finance sample review flows with explicit limitations', async ({ page }) => {
  await page.goto('/staff/bookings/demo-stay-001/stay')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await expect(page.getByRole('heading', { name: 'Stay operations.' })).toBeVisible()
  await page.getByLabel('Tambahan malam').fill('2')
  await page.getByRole('button', { name: 'Simulasikan perpanjangan' }).click()
  await expect(page.getByText(/status pembayaran belum dikonfirmasi/i)).toBeVisible()
  await page.goto('/staff/finance/refunds')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await page.getByLabel('Booking ID').fill('demo-stay-001')
  await page.getByLabel('Nominal IDR').fill('250000')
  await page.getByLabel('Alasan').fill('Refund sample valid')
  await page.getByRole('button', { name: 'Tinjau refund sample' }).click()
  await page.getByRole('button', { name: 'Konfirmasi simulasi' }).click()
  await expect(page.getByText(/berstatus pending/)).toBeVisible()
})

test('shows catalog detail and clearly separates base price from final quote', async ({ page }) => {
  await page.goto('/booking/rooms/deluxe-king-bay')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await expect(page.getByRole('heading', { name: 'Deluxe King Bay Window' })).toBeVisible()
  await page.getByRole('button', { name: 'Periksa tanggal' }).click()
  await expect(page.getByText(/total final mengikuti quote/i)).toBeVisible()
})

test('applies sample staff permissions and keeps management actions offline', async ({ page }) => {
  await page.goto('/staff/login')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await page.getByLabel('Peran sample').selectOption('receptionist')
  await page.getByRole('button', { name: 'Masuk preview' }).click()
  await expect(page.getByRole('link', { name: 'Front desk' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Finance' })).toHaveCount(0)
  await page.goto('/staff/login')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await page.getByLabel('Peran sample').selectOption('gm_admin')
  await page.getByRole('button', { name: 'Masuk preview' }).click()
  await page.goto('/staff/channels')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await page.getByRole('button', { name: 'Simulasikan retry' }).nth(1).click()
  await expect(page.getByText(/Tidak ada pesan yang dikirim ke channel/)).toBeVisible()
  await page.goto('/staff/configuration')
  await expect(page.locator('html')).toHaveAttribute('data-nuxt-ready', 'true')
  await page.getByRole('button', { name: 'Simpan simulasi' }).click()
  await expect(page.getByText(/hanya disimpan sebagai simulasi/)).toBeVisible()
})

test('keeps booking motion usable with reduced motion and exposes quote feedback', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/booking/results?v=1&check_in=2026-10-03&check_out=2026-10-04&guests=1')
  await expect(page.getByRole('heading', { name: 'Kamar dan paket' })).toBeVisible()
  const reveal = page.locator('.section-reveal').first()
  await expect.poll(() => reveal.evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  await expect.poll(() => page.locator('.button').first().evaluate(element => getComputedStyle(element).transitionDuration)).toBe('0s')

  const firstCard = page.locator('.room-card').first()
  await firstCard.getByLabel('Varian / tempat tidur').selectOption('deluxe-king-bay')
  await firstCard.getByLabel('Room Only').check()
  await firstCard.getByRole('button', { name: 'Pilih kamar & paket' }).click()
  await expect(firstCard.getByText(/Dipilih: Deluxe King Bay Window/)).toBeVisible()
  const navigation = page.waitForURL(/\/booking\/guest$/)
  await page.getByRole('button', { name: 'Lanjut' }).click()
  await expect(page.getByText('Menyiapkan total pilihan…')).toBeVisible()
  await navigation
})
