<script setup lang="ts">
import { sampleAudits } from '~/data/management-scenarios'
import type { AuditSnapshot } from '~/types/management'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Audit activity' })
const result = ref(''); const role = ref(''); const selected = ref<AuditSnapshot | null>(null)
const activeFilters = computed(() => [result.value ? `Hasil ${result.value}` : '', role.value ? `Role ${role.value}` : ''].filter(Boolean))
const filtered = computed(() => sampleAudits.filter(item => (!result.value || item.result === result.value) && (!role.value || item.role === role.value)))
const changes = computed(() => { if (!selected.value) return []; const keys = new Set([...Object.keys(selected.value.before || {}), ...Object.keys(selected.value.after || {})]); return [...keys].map(key => ({ label: key, before: selected.value?.before?.[key] || '—', after: selected.value?.after?.[key] || '—' })) })
function reset() { result.value = ''; role.value = '' }
</script>
<template><div class="container ops-page"><StaffPageHeader eyebrow="Identity & controls" title="Audit activity" description="Actor, target, waktu, dan hasil perubahan operasional." /><UiInlineAlert tone="info">Audit log live belum terintegrasi. Data berikut hanya fixture tersanitasi dan bukan server audit trail.</UiInlineAlert><StaffFilterBar :active="activeFilters" :result-label="`${filtered.length} event sample`" @reset="reset"><div class="field"><label for="audit-result">Hasil</label><select id="audit-result" v-model="result"><option value="">Semua</option><option value="success">Success</option><option value="denied">Denied</option></select></div><div class="field"><label for="audit-role">Role</label><select id="audit-role" v-model="role"><option value="">Semua</option><option value="receptionist">Receptionist</option><option value="housekeeping">Housekeeping</option><option value="gm_admin">GM admin</option></select></div></StaffFilterBar><StaffDataState v-if="!filtered.length && activeFilters.length" no-results @reset="reset" /><div v-else class="ops-grid"><article v-for="item in filtered" :key="item.id" class="ops-card" :class="{ 'ops-card--selected': selected?.id === item.id }"><div class="ops-card__top"><strong>{{ item.action }}</strong><StaffStatusBadge :label="item.result" :status="item.result" /></div><p>{{ item.actor }} · {{ item.role }}</p><p>{{ item.resourceType }}: {{ item.target }}</p><time>{{ new Date(item.occurredAt).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' }) }}</time><BrandButton @click="selected = item">Lihat perubahan</BrandButton></article></div><StaffDetailDrawer id="audit-detail" :open="Boolean(selected)" :title="selected?.action || 'Detail audit'" eyebrow="Audit sample" @close="selected = null"><div v-if="selected" class="stack"><p><strong>{{ selected.actor }}</strong><br>{{ selected.role }}</p><p>{{ selected.resourceType }} · {{ selected.target }}</p><StaffStatusBadge :label="selected.result" :status="selected.result" /><StaffChangeReview v-if="changes.length" :items="changes" /><UiInlineAlert tone="info">Nilai sensitif dan free text tidak dimasukkan ke fixture audit ini.</UiInlineAlert></div></StaffDetailDrawer></div></template>
