<script setup lang="ts">
import type { FeatureFlagSnapshot } from '~/types/management'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Hotel configuration' })
const apiMode = computed(() => useRuntimeConfig().public.operationsMode === 'api')
const form = reactive({ checkIn: '15:00', checkOut: '12:00', timezone: 'Asia/Jakarta', cancellation: 'Pembatalan mengikuti deadline pada quote dan booking.' })
const flags = ref<FeatureFlagSnapshot[]>([]); const loading = ref(false); const error = ref(''); const notice = ref('')
async function loadFlags() {
  if (!apiMode.value) return
  loading.value = true; error.value = ''
  try { flags.value = (await $fetch<{ total: number, flags: FeatureFlagSnapshot[] }>('/api/bff/staff/admin/feature-flags')).flags || [] }
  catch (cause) { const value = cause as { statusMessage?: string, data?: { statusMessage?: string } }; error.value = value.data?.statusMessage || value.statusMessage || 'Feature flags belum dapat dimuat.' }
  finally { loading.value = false }
}
function save() { notice.value = 'Konfigurasi hotel hanya disimpan sebagai simulasi pada layar ini.' }
onMounted(loadFlags)
</script>
<template><div class="container ops-page"><StaffPageHeader eyebrow="Administration" title="Configuration" description="Pisahkan feature flags runtime dari kebijakan hotel yang menjadi snapshot booking." /><UiInlineAlert v-if="notice" tone="info" live>{{ notice }}</UiInlineAlert><section class="stack"><div><p class="eyebrow">Runtime controls</p><h2>Feature flags</h2><p class="muted">Allowed roles membatasi flag, tetapi tidak menambah izin Casbin.</p></div><UiInlineAlert v-if="!apiMode" tone="info">Feature flags live hanya tersedia pada mode API dengan sesi GM admin.</UiInlineAlert><StaffDataState v-else-if="loading" loading loading-label="Memuat feature flags…" /><StaffDataState v-else-if="error" :error="error" @retry="loadFlags" /><StaffDataState v-else-if="!flags.length" empty empty-label="Belum ada feature flag pada response." /><div v-else class="ops-grid config-flags"><article v-for="flag in flags" :key="flag.key" class="ops-card"><div class="ops-card__top"><div><p class="eyebrow">{{ flag.key }}</p><h3>{{ flag.name }}</h3></div><StaffStatusBadge :label="flag.enabled ? 'Enabled' : 'Disabled'" :status="flag.enabled ? 'healthy' : 'attention'" /></div><p>{{ flag.description }}</p><p class="muted">Peran: {{ flag.allowed_roles?.join(', ') || 'Semua role yang lolos RBAC' }}</p><small>Diperbarui {{ new Date(flag.updated_at).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' }) }} oleh {{ flag.updated_by }}</small><BrandButton disabled>Perubahan live dikunci</BrandButton></article></div></section><section class="stack"><div><p class="eyebrow">Hotel policy sample</p><h2>Waktu dan pembatalan</h2></div><UiInlineAlert tone="info">Endpoint hotel policy belum tersedia. Form ini memperagakan validation dan unsaved state tanpa mengubah booking.</UiInlineAlert><form class="panel stack" @submit.prevent="save"><div class="ops-grid config-grid"><div class="field"><label for="config-check-in">Check-in</label><input id="config-check-in" v-model="form.checkIn" type="time"></div><div class="field"><label for="config-check-out">Check-out</label><input id="config-check-out" v-model="form.checkOut" type="time"></div><div class="field"><label for="config-timezone">Timezone</label><input id="config-timezone" v-model="form.timezone" readonly></div></div><div class="field"><label for="config-cancellation">Kebijakan pembatalan</label><textarea id="config-cancellation" v-model="form.cancellation" rows="5"></textarea></div><BrandButton type="submit" dark>Simpan simulasi</BrandButton></form></section></div></template>
<style scoped>.config-grid { grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }.config-flags { grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); }</style>
