<script setup lang="ts">
import type { CleanlinessStatus, OperationalRoom, RoomBoard } from '~/types/operations'
import { cleanlinessLabels, jakartaDate, operationsMessage } from '~/utils/operations'
import { decodeStaffFilterQuery, encodeStaffFilterQuery, type StaffFilterSchema } from '~/utils/staff-filter-query'
import { createLatestRequestOwner } from '~/utils/latest-request'
import { preserveOperationsQAQuery } from '~/utils/qa-controls'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Housekeeping' })
const route = useRoute(); const client = useOperationsClient()
const apiMode = computed(() => useRuntimeConfig().public.operationsMode === 'api')
const statuses = Object.keys(cleanlinessLabels) as CleanlinessStatus[]
const schema = { floor: { type: 'integer', default: 0, min: 0, max: 999 }, status: { type: 'enum', default: '', values: statuses }, room_type: { type: 'string', default: '', maxLength: 64 } } satisfies StaffFilterSchema
const initialFilters = decodeStaffFilterQuery(schema, route.query)
const board = ref<RoomBoard | null>(null); const loading = ref(false); const error = ref(''); const notice = ref(''); const lastSuccess = ref<Date | null>(null); const requests = createLatestRequestOwner()
const filters = reactive({ floor: Number(initialFilters.floor), status: String(initialFilters.status), roomTypeId: String(initialFilters.room_type) })
const selected = ref<OperationalRoom | null>(null); const nextStatus = ref<CleanlinessStatus>('cleaning'); const notes = ref(''); const submitting = ref(false)
const ooo = reactive({ roomNumber: '', startDate: jakartaDate(), endDate: '', reason: '' })
const activeFilters = computed(() => [filters.floor ? `Lantai ${filters.floor}` : '', filters.status ? cleanlinessLabels[filters.status as CleanlinessStatus] : '', filters.roomTypeId ? `Tipe ${filters.roomTypeId}` : ''].filter(Boolean))

async function load() {
  const current = requests.begin(); const selectedNumber = selected.value?.roomNumber; loading.value = true; error.value = ''; try { const result = await client.getRoomBoard({ floor: filters.floor || undefined, status: filters.status || undefined, roomTypeId: filters.roomTypeId || undefined }); if (requests.isLatest(current)) { board.value = result; lastSuccess.value = new Date(); if (selectedNumber) selected.value = result.rooms.find(room => room.roomNumber === selectedNumber) || selected.value } }
  catch (cause) { if (requests.isLatest(current)) error.value = operationsMessage(cause, 'Board kamar belum dapat dimuat.') }
  finally { if (requests.isLatest(current)) loading.value = false }
}
async function applyFilters() { await navigateTo({ path: route.path, query: { ...preserveOperationsQAQuery(route.query), ...encodeStaffFilterQuery(schema, { floor: filters.floor, status: filters.status, room_type: filters.roomTypeId }) } }, { replace: true }); await load() }
async function resetFilters() { Object.assign(filters, { floor: 0, status: '', roomTypeId: '' }); await applyFilters() }
function edit(room: OperationalRoom) { selected.value = room; nextStatus.value = room.status === 'vacant_dirty' ? 'cleaning' : room.status === 'cleaning' ? 'vacant_clean' : room.status === 'vacant_clean' ? 'inspected' : room.status; notes.value = room.maintenanceNotes }
async function updateStatus() {
  if (!selected.value) return; submitting.value = true; error.value = ''; try { await client.updateRoomStatus(selected.value.roomNumber, nextStatus.value, notes.value); notice.value = `Simulasi status kamar ${selected.value.roomNumber} diperbarui.`; selected.value = null; await load() }
  catch (cause) { error.value = operationsMessage(cause, 'Status kamar tidak dapat diperbarui.') }
  finally { submitting.value = false }
}
async function markOOO() {
  submitting.value = true; error.value = ''; try { await client.markOutOfOrder(ooo.roomNumber, { startDate: ooo.startDate, endDate: ooo.endDate, reason: ooo.reason }); notice.value = `Simulasi kamar ${ooo.roomNumber} ditandai rusak berat.`; ooo.roomNumber = ''; ooo.reason = ''; await load() }
  catch (cause) { error.value = operationsMessage(cause, 'Kamar tidak dapat ditandai rusak berat.') }
  finally { submitting.value = false }
}
watch(() => route.query, (query) => { const value = decodeStaffFilterQuery(schema, query); Object.assign(filters, { floor: Number(value.floor), status: String(value.status), roomTypeId: String(value.room_type) }) }, { deep: true })
onMounted(load); onBeforeUnmount(requests.invalidate)
</script>

<template><div class="container ops-page"><StaffPageHeader eyebrow="Operasional kamar" title="Housekeeping board" description="Ringkasan mengikuti filter aktif. Bersih masih memerlukan inspeksi sebelum check-in." />
  <UiInlineAlert v-if="notice" tone="info" live>{{ notice }}</UiInlineAlert><UiInlineAlert v-if="error && board" tone="error" live>{{ error }}</UiInlineAlert>
  <StaffFilterBar :active="activeFilters" :busy="loading" :result-label="board ? `${board.totalRooms} kamar pada hasil filter` : ''" @apply="applyFilters" @reset="resetFilters"><div class="field"><label for="floor">Lantai</label><input id="floor" v-model.number="filters.floor" type="number" min="0" placeholder="Semua" /></div><div class="field"><label for="hk-status">Status</label><select id="hk-status" v-model="filters.status"><option value="">Semua</option><option v-for="status in statuses" :key="status" :value="status">{{ cleanlinessLabels[status] }}</option></select></div><div class="field"><label for="room-type">ID tipe kamar</label><input id="room-type" v-model.trim="filters.roomTypeId" /></div></StaffFilterBar><StaffFreshnessStatus v-if="board" :loading="loading" :stale="Boolean(error)" :last-success="lastSuccess" />
  <div v-if="board" class="ops-metrics"><div v-for="status in statuses" :key="status" class="ops-metric"><strong>{{ board.summary[status] || 0 }}</strong>{{ cleanlinessLabels[status] }}</div></div><p v-if="board" role="status">{{ board.totalRooms }} kamar pada hasil filter.</p>
  <div class="ops-split"><section><StaffDataState v-if="loading && !board" loading /><StaffDataState v-else-if="error && !board" :error="error" @retry="load" /><StaffDataState v-else-if="board && !board.rooms.length && activeFilters.length" no-results @reset="resetFilters" /><StaffDataState v-else-if="board && !board.rooms.length" empty empty-label="Belum ada kamar pada board." /><div v-else class="ops-grid ops-grid--rooms"><article v-for="room in board?.rooms" :key="room.roomNumber" class="ops-card" :class="{ 'ops-card--selected': selected?.roomNumber === room.roomNumber }"><div class="ops-card__top"><div><p class="eyebrow">Kamar {{ room.roomNumber }} · L{{ room.floor }}</p><h3>{{ room.roomTypeName }}</h3></div><StaffStatusBadge :label="cleanlinessLabels[room.status]" :status="room.status" /></div><p v-if="room.guestName">Tamu: {{ room.guestName }}</p><p v-if="room.maintenanceNotes" class="muted">{{ room.maintenanceNotes }}</p><small>Diperbarui {{ new Date(room.updatedAt).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' }) }}</small><BrandButton @click="edit(room)">{{ selected?.roomNumber === room.roomNumber ? 'Sedang dipilih' : 'Ubah status' }}</BrandButton></article></div></section>
    <aside class="stack"><form class="panel stack" @submit.prevent="markOOO"><p class="eyebrow">Khusus GM</p><h2>Rusak berat</h2><UiInlineAlert tone="info">Preview sample. Mutasi live tetap dikunci.</UiInlineAlert><div class="field"><label for="ooo-room">Nomor kamar</label><input id="ooo-room" v-model.trim="ooo.roomNumber" required /></div><div class="two-col"><div class="field"><label for="ooo-start">Mulai</label><input id="ooo-start" v-model="ooo.startDate" type="date" required /></div><div class="field"><label for="ooo-end">Selesai (eksklusif)</label><input id="ooo-end" v-model="ooo.endDate" type="date" required /></div></div><div class="field"><label for="ooo-reason">Alasan</label><textarea id="ooo-reason" v-model="ooo.reason" required rows="3" /></div><BrandButton type="submit" :loading="submitting" :disabled="apiMode">Simpan simulasi OOO</BrandButton></form></aside>
  </div><StaffDetailDrawer id="housekeeping-detail" :open="Boolean(selected)" :title="selected ? `Kamar ${selected.roomNumber}` : 'Detail kamar'" eyebrow="Housekeeping" :busy="submitting" @close="selected = null"><form v-if="selected" class="stack" @submit.prevent="updateStatus"><div class="ops-card"><div class="ops-card__top"><div><p class="eyebrow">Lantai {{ selected.floor }}</p><h3>{{ selected.roomTypeName }}</h3></div><StaffStatusBadge :label="cleanlinessLabels[selected.status]" :status="selected.status" /></div><p v-if="selected.guestName">Tamu: {{ selected.guestName }}</p><p class="muted">{{ selected.maintenanceNotes || 'Tanpa catatan maintenance.' }}</p><small>Diperbarui oleh {{ selected.updatedBy }}</small></div><UiInlineAlert v-if="apiMode" tone="info">Data live dapat dibaca. Mutation status masih dikunci sampai gate operasional diaktifkan.</UiInlineAlert><div class="field"><label for="next-status">Status berikutnya</label><select id="next-status" v-model="nextStatus"><option v-for="status in statuses" :key="status" :value="status">{{ cleanlinessLabels[status] }}</option></select></div><div class="field"><label for="status-notes">Catatan</label><textarea id="status-notes" v-model="notes" rows="4" /></div><UiInlineAlert tone="info">Perubahan: {{ cleanlinessLabels[selected.status] }} → {{ cleanlinessLabels[nextStatus] }}.</UiInlineAlert><div class="ops-actions"><BrandButton type="submit" dark :loading="submitting" :disabled="apiMode">Simpan simulasi</BrandButton><BrandButton :disabled="submitting" @click="selected = null">Batal</BrandButton></div></form></StaffDetailDrawer></div></template>
