<script setup lang="ts">
import { roomVariants } from '~/data/rooms'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Inventory preview' })
const draft = reactive({ roomId: roomVariants[0]?.id || '', startDate: '2026-10-04', endDate: '2026-10-05', allotment: 3, reason: '' })
const { dirty, accept, restore } = useUnsavedChanges(() => draft)
const review = ref(false); const notice = ref('')
const nights = computed(() => Math.max(0, Math.round((Date.parse(`${draft.endDate}T00:00:00Z`) - Date.parse(`${draft.startDate}T00:00:00Z`)) / 86400000)))
const currentRoom = computed(() => roomVariants.find(room => room.id === draft.roomId))
const reviewItems = computed(() => [{ label: 'Tipe kamar', before: currentRoom.value?.name || '—', after: currentRoom.value?.name || '—' }, { label: 'Rentang', before: 'Belum diterapkan', after: `${draft.startDate}–${draft.endDate} (${nights.value} malam)` }, { label: 'Allotment', before: '3 kamar sample', after: `${draft.allotment} kamar sample` }, { label: 'Alasan', before: '—', after: draft.reason }])
function discard() { Object.assign(draft, restore()); notice.value = 'Perubahan inventory dibuang.' }
function apply() { accept(); review.value = false; notice.value = 'Perubahan allotment hanya disimulasikan; inventory live tidak berubah.' }
onBeforeRouteLeave(() => !dirty.value || window.confirm('Tinggalkan editor dan buang perubahan inventory?'))
</script>
<template><div class="container ops-page"><StaffPageHeader eyebrow="Inventory controls" title="Inventory" description="Preview allotment per tipe kamar dan rentang tanggal tanpa mencampurnya dengan status kebersihan kamar."><template #actions><StaffStatusBadge v-if="dirty" label="Belum disimpan" status="pending" /></template></StaffPageHeader><UiInlineAlert tone="info">Mode sample. Management inventory backend belum tersedia; availability publik tetap authoritative untuk booking.</UiInlineAlert><UiInlineAlert v-if="notice" tone="info" live>{{ notice }}</UiInlineAlert><form class="panel stack" @submit.prevent="review = true"><div class="ops-grid"><div class="field"><label for="inventory-room">Room type</label><select id="inventory-room" v-model="draft.roomId"><option v-for="room in roomVariants" :key="room.id" :value="room.id">{{ room.name }}</option></select></div><div class="field"><label for="inventory-start">Mulai</label><input id="inventory-start" v-model="draft.startDate" type="date" required></div><div class="field"><label for="inventory-end">Selesai (eksklusif)</label><input id="inventory-end" v-model="draft.endDate" type="date" :min="draft.startDate" required></div><div class="field"><label for="inventory-count">Allotment sample</label><input id="inventory-count" v-model.number="draft.allotment" type="number" min="0" required></div></div><div class="field"><label for="inventory-reason">Alasan</label><textarea id="inventory-reason" v-model.trim="draft.reason" rows="3" required /></div><UiInlineAlert :tone="nights > 0 ? 'info' : 'error'">Rentang memengaruhi {{ nights }} malam. Jumlah ini bukan sellable inventory authoritative.</UiInlineAlert><div class="ops-actions"><BrandButton type="submit" dark :disabled="!dirty || nights < 1">Tinjau dampak</BrandButton><BrandButton :disabled="!dirty" @click="discard">Buang perubahan</BrandButton></div></form><StaffActionDialog id="inventory-review" :open="review" title="Konfirmasi simulasi inventory" @close="review = false"><StaffChangeReview :items="reviewItems" /><UiInlineAlert tone="info">Simulasi ini tidak mengubah availability atau quote live.</UiInlineAlert><template #actions><BrandButton dark @click="apply">Terapkan simulasi</BrandButton><BrandButton @click="review = false">Kembali</BrandButton></template></StaffActionDialog></div></template>
