<script setup lang="ts">
import { samplePromos } from '~/data/management-scenarios'
import type { PromoSnapshot } from '~/types/management'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Promo preview' })
const promos = ref(structuredClone(samplePromos)); const draft = reactive<PromoSnapshot>({ code: '', type: 'percent', value: 10, status: 'scheduled', startsAt: '2026-10-04', endsAt: '2026-10-31' })
const { dirty, accept, restore } = useUnsavedChanges(() => draft); const notice = ref(''); const review = ref(false)
const valid = computed(() => draft.code.trim().length > 0 && draft.code.length <= 24 && draft.value > 0 && (draft.type !== 'percent' || draft.value <= 100) && draft.startsAt < draft.endsAt)
const reviewItems = computed(() => [{ label: 'Kode', before: 'Promo baru', after: draft.code.toUpperCase() }, { label: 'Nilai', before: '—', after: draft.type === 'percent' ? `${draft.value}%` : `IDR ${draft.value.toLocaleString('id-ID')}` }, { label: 'Periode', before: '—', after: `${draft.startsAt}–${draft.endsAt}` }])
function discard() { Object.assign(draft, restore()); notice.value = 'Draft promo dibuang.' }
function save() { promos.value.unshift({ ...structuredClone(toRaw(draft)), code: draft.code.toUpperCase() }); accept(); review.value = false; notice.value = 'Promo baru hanya dibuat sebagai simulasi.' }
onBeforeRouteLeave(() => !dirty.value || window.confirm('Tinggalkan editor dan buang draft promo?'))
</script>
<template><div class="container ops-page"><StaffPageHeader eyebrow="Revenue workspace" title="Promo" description="Jadwal, nilai, dan status promo ditinjau sebelum diterapkan ke pricing."><template #nav><div class="ops-subnav"><NuxtLink to="/staff/rates">Rate plans</NuxtLink><NuxtLink to="/staff/promos">Promo</NuxtLink></div></template><template #actions><StaffStatusBadge v-if="dirty" label="Belum disimpan" status="pending" /></template></StaffPageHeader><UiInlineAlert tone="info">Validasi kode promo pada quote publik tetap menjadi sumber harga final. Management di sini masih sample.</UiInlineAlert><UiInlineAlert v-if="notice" tone="info" live>{{ notice }}</UiInlineAlert><div class="ops-split"><section class="stack"><article v-for="promo in promos" :key="`${promo.code}-${promo.startsAt}`" class="ops-card"><div class="ops-card__top"><h3>{{ promo.code }}</h3><StaffStatusBadge :label="promo.status" :status="promo.status" /></div><p>{{ promo.type === 'percent' ? `${promo.value}%` : `IDR ${promo.value.toLocaleString('id-ID')}` }} · {{ promo.startsAt }}–{{ promo.endsAt }}</p></article></section><form class="panel stack" @submit.prevent="review = true"><h2>Buat promo sample</h2><div class="field"><label for="promo-code">Kode</label><input id="promo-code" v-model.trim="draft.code" required maxlength="24"></div><div class="field"><label for="promo-type">Tipe</label><select id="promo-type" v-model="draft.type"><option value="percent">Persen</option><option value="fixed">Nominal IDR</option></select></div><div class="field"><label for="promo-value">Nilai</label><input id="promo-value" v-model.number="draft.value" type="number" min="1" :max="draft.type === 'percent' ? 100 : undefined" required></div><div class="two-col"><div class="field"><label for="promo-start">Mulai</label><input id="promo-start" v-model="draft.startsAt" type="date" required></div><div class="field"><label for="promo-end">Selesai</label><input id="promo-end" v-model="draft.endsAt" type="date" :min="draft.startsAt" required></div></div><UiInlineAlert v-if="dirty && !valid" tone="error">Lengkapi kode, nilai, dan rentang tanggal yang valid.</UiInlineAlert><div class="ops-actions"><BrandButton type="submit" dark :disabled="!dirty || !valid">Tinjau promo</BrandButton><BrandButton :disabled="!dirty" @click="discard">Buang draft</BrandButton></div></form></div><StaffActionDialog id="promo-review" :open="review" title="Konfirmasi promo sample" @close="review = false"><StaffChangeReview :items="reviewItems" /><UiInlineAlert tone="info">Stacking, blackout dan usage limit belum memiliki kontrak backend.</UiInlineAlert><template #actions><BrandButton dark @click="save">Simpan simulasi</BrandButton><BrandButton @click="review = false">Kembali</BrandButton></template></StaffActionDialog></div></template>
