<script setup lang="ts">
import { ratePlans } from '~/data/rate-plans'
import { formatMoney, rupiah } from '~/utils/money'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Rate plans preview' })
const prices = reactive<Record<string, number>>({ room_only: 1000000, bed_and_breakfast: 1150000 })
const original = reactive({ ...prices }); const { dirty, accept, restore } = useUnsavedChanges(() => prices)
const notice = ref(''); const review = ref(false)
const reviewItems = computed(() => ratePlans.map(rate => ({ label: rate.name, before: formatMoney(rupiah(original[rate.id] || 0)), after: formatMoney(rupiah(prices[rate.id] || 0)) })))
function discard() { Object.assign(prices, restore()); notice.value = 'Perubahan rate dibuang.' }
function save() { Object.assign(original, prices); accept(); review.value = false; notice.value = 'Rate plan disimpan sebagai simulasi. Quote live tidak berubah.' }
onBeforeRouteLeave(() => !dirty.value || window.confirm('Tinggalkan editor dan buang perubahan rate?'))
</script>
<template><div class="container ops-page"><StaffPageHeader eyebrow="Revenue workspace" title="Rate plans" description="Bandingkan benefit dan harga dasar sebelum membuat simulasi dampak quote."><template #nav><div class="ops-subnav"><NuxtLink to="/staff/rates">Rate plans</NuxtLink><NuxtLink to="/staff/promos">Promo</NuxtLink></div></template><template #actions><StaffStatusBadge v-if="dirty" label="Belum disimpan" status="pending" /></template></StaffPageHeader><UiInlineAlert tone="info">Mode sample sampai API management rate tersedia. Harga berikut bukan quote final.</UiInlineAlert><UiInlineAlert v-if="notice" tone="info" live>{{ notice }}</UiInlineAlert><div class="ops-grid"><article v-for="rate in ratePlans" :key="rate.id" class="ops-card"><div class="ops-card__top"><h2>{{ rate.name }}</h2><StaffStatusBadge :label="rate.breakfast ? 'Sarapan' : 'Tanpa sarapan'" /></div><ul><li v-for="benefit in rate.benefits" :key="benefit">{{ benefit }}</li></ul><div class="field"><label :for="`price-${rate.id}`">Harga dasar sample</label><input :id="`price-${rate.id}`" v-model.number="prices[rate.id]" type="number" min="0" step="1"></div><strong>{{ formatMoney(rupiah(prices[rate.id] || 0)) }}</strong></article></div><div class="ops-actions"><BrandButton dark :disabled="!dirty" @click="review = true">Tinjau perubahan</BrandButton><BrandButton :disabled="!dirty" @click="discard">Buang perubahan</BrandButton></div><StaffActionDialog id="rate-review" :open="review" title="Konfirmasi rate sample" @close="review = false"><StaffChangeReview :items="reviewItems" /><UiInlineAlert tone="info">Pricing publik dan quote terkunci tidak berubah.</UiInlineAlert><template #actions><BrandButton dark @click="save">Simpan simulasi</BrandButton><BrandButton @click="review = false">Kembali</BrandButton></template></StaffActionDialog></div></template>
