<script setup lang="ts">
import { validateGuest } from '~/utils/validation'

definePageMeta({ layout: 'booking' }); useSeoMeta({ title: 'Detail tamu' })
const { draft } = useBookingDraft(); const errors = ref<Record<string, string>>({})
onMounted(() => { if (!draft.value.selectedQuote) navigateTo('/booking') })
async function submit() { errors.value = validateGuest(draft.value.guest); if (!Object.keys(errors.value).length) await navigateTo('/booking/review') }
</script>
<template><div class="container"><BookingSteps :current="2" /><UiInlineAlert v-if="!draft.selectedQuote" tone="error">Sesi demo tidak memiliki quote. Pilih kamar kembali. <BrandButton to="/booking">Mulai lagi</BrandButton></UiInlineAlert><div v-else class="checkout-grid"><form class="stack" novalidate @submit.prevent="submit"><div><p class="eyebrow">Detail tamu</p><h1>Siapa yang pulang?</h1></div><UiFormField id="full-name" label="Nama lengkap" :error="errors.fullName"><template #default="{ describedby }"><input id="full-name" v-model="draft.guest.fullName" autocomplete="name" :aria-describedby="describedby" :aria-invalid="Boolean(errors.fullName)"></template></UiFormField><UiFormField id="email" label="Email" :error="errors.email" hint="Tidak ada email yang dikirim dalam demo."><template #default="{ describedby }"><input id="email" v-model="draft.guest.email" type="email" autocomplete="email" :aria-describedby="describedby" :aria-invalid="Boolean(errors.email)"></template></UiFormField><UiFormField id="requests" label="Permintaan khusus" :error="errors.specialRequests" hint="Bergantung ketersediaan dan bukan jaminan."><template #default="{ describedby }"><textarea id="requests" v-model="draft.guest.specialRequests" rows="5" maxlength="500" :aria-describedby="describedby" /><small>{{ [...draft.guest.specialRequests].length }}/500</small></template></UiFormField><BrandButton type="submit">Tinjau booking</BrandButton></form><BookingSummary :quote="draft.selectedQuote" /></div></div></template>
<style scoped>.checkout-grid { display: grid; gap: 36px; }.checkout-grid h1 { font-size: clamp(3rem, 7vw, 5.5rem); } @media (min-width: 900px) { .checkout-grid { grid-template-columns: 1fr 420px; }.summary { position: sticky; top: 100px; } }</style>
