<script setup lang="ts">
import type { PaymentCase } from '~/types/operations'
import { formatMoney, money } from '~/utils/money'
import { operationsMessage } from '~/utils/operations'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Kasus pembayaran' })
const client = useOperationsClient(); const cases = ref<PaymentCase[]>([]); const count = ref(0); const status = ref(''); const selected = ref<PaymentCase | null>(null); const action = ref('manual_adjustment'); const notes = ref(''); const loading = ref(false); const busy = ref(false); const error = ref(''); const notice = ref('')
const apiMode = computed(() => useRuntimeConfig().public.operationsMode === 'api')
function displayMoney(item: PaymentCase) { return item.currency === 'IDR' ? formatMoney(money(item.amountMinor, 0)) : `${item.currency} ${item.amountMinor}` }
async function load() {
  loading.value = true; error.value = ''; try { const result = await client.getFinanceCases(status.value || undefined, 50); cases.value = result.cases; count.value = result.total }
  catch (cause) { error.value = operationsMessage(cause, 'Kasus pembayaran belum dapat dimuat.') }
  finally { loading.value = false }
}
async function resolve() {
  if (!selected.value) return; busy.value = true; error.value = ''; try { await client.resolveCase(selected.value.id, action.value, notes.value); notice.value = 'Resolusi sample dicatat. Ini tidak mengeksekusi refund atau alokasi kamar.'; selected.value = null; await load() }
  catch (cause) { error.value = operationsMessage(cause, 'Resolusi belum dapat dicatat.') }
  finally { busy.value = false }
}
onMounted(load)
</script>
<template><div class="container ops-page"><StaffPageHeader eyebrow="Payment cases" title="Kasus pembayaran" description="Pilih kasus, periksa referensi dan nominal, lalu catat keputusan secara eksplisit."><template #nav><div class="ops-subnav"><NuxtLink to="/staff/finance">Ringkasan</NuxtLink><NuxtLink to="/staff/finance/cases">Kasus</NuxtLink><NuxtLink to="/staff/finance/refunds">Refund</NuxtLink></div></template></StaffPageHeader><UiInlineAlert v-if="notice" tone="info" live>{{ notice }}</UiInlineAlert><UiInlineAlert v-if="error && cases.length" tone="error" live>{{ error }}</UiInlineAlert><form class="ops-toolbar" @submit.prevent="load"><div class="field"><label for="case-status">Status</label><select id="case-status" v-model="status"><option value="">Semua</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></div><BrandButton type="submit" :loading="loading" loading-label="Menerapkan…">Terapkan</BrandButton></form><p>{{ count }} baris pada response ini; bukan total seluruh database.</p>
<section class="stack"><StaffDataState v-if="loading && !cases.length" loading loading-label="Memuat kasus…" /><StaffDataState v-else-if="error && !cases.length" :error="error" @retry="load" /><article v-for="item in cases" :key="item.id" class="ops-card" :class="{ 'ops-card--selected': selected?.id === item.id }"><div class="ops-card__top"><div><p class="eyebrow">{{ item.caseType }}</p><h3>{{ item.bookingId || 'Booking tidak terhubung' }}</h3></div><StaffStatusBadge :label="item.status" :status="item.status" /></div><strong>{{ displayMoney(item) }}</strong><p>{{ item.notes }}</p><small>Ref provider: {{ item.providerReference }}</small><BrandButton @click="selected = item; notes = item.notes">{{ selected?.id === item.id ? 'Sedang ditinjau' : 'Tinjau resolusi' }}</BrandButton></article><StaffDataState v-if="!loading && !cases.length && !error" empty empty-label="Tidak ada kasus pada filter ini." /></section><StaffDetailDrawer id="finance-case-detail" :open="Boolean(selected)" :title="selected ? `Kasus ${selected.id}` : 'Detail kasus'" eyebrow="Payment case" :busy="busy" @close="selected = null"><form v-if="selected" class="stack" @submit.prevent="resolve"><div class="ops-card"><div class="ops-card__top"><div><p class="eyebrow">{{ selected.caseType }}</p><h3>{{ selected.bookingId || 'Booking tidak terhubung' }}</h3></div><StaffStatusBadge :label="selected.status" :status="selected.status" /></div><strong>{{ displayMoney(selected) }}</strong><p>Ref provider: {{ selected.providerReference }}</p></div><UiInlineAlert tone="info">{{ apiMode ? 'Detail live dapat dibaca. Mutation resolusi masih dikunci sampai semantics tindakan disepakati.' : 'Aksi sample hanya mencatat resolusi. Refund atau realokasi tetap workflow terpisah.' }}</UiInlineAlert><div class="field"><label for="case-action">Tindakan tercatat</label><select id="case-action" v-model="action"><option value="manual_adjustment">Penyesuaian manual</option><option value="refund">Refund dicatat</option><option value="reallocate">Realokasi dicatat</option><option value="dismiss">Tutup tanpa tindakan</option></select></div><div class="field"><label for="case-notes">Catatan</label><textarea id="case-notes" v-model="notes" rows="5" required /></div><div class="ops-actions"><BrandButton type="submit" dark :loading="busy" :disabled="apiMode">Simpan simulasi</BrandButton><BrandButton :disabled="busy" @click="selected = null">Batal</BrandButton></div></form></StaffDetailDrawer></div></template>
