<script setup lang="ts">
import { sampleChannels } from '~/data/management-scenarios'
import type { ChannelSnapshot } from '~/types/management'

definePageMeta({ layout: 'staff' }); useSeoMeta({ title: 'Channel sync preview' })
const status = ref(''); const selected = ref<ChannelSnapshot | null>(null); const review = ref(false); const notice = ref('')
const activeFilters = computed(() => status.value ? [`Status ${status.value}`] : [])
const filtered = computed(() => sampleChannels.filter(item => !status.value || item.status === status.value))
function reset() { status.value = '' }
function openRetry(item: ChannelSnapshot) { selected.value = item; review.value = true }
function retry() { if (!selected.value) return; notice.value = `Retry ${selected.value.name} disimulasikan. Status tidak diubah sebelum acknowledgment authoritative.`; review.value = false }
</script>
<template><div class="container ops-page"><StaffPageHeader eyebrow="Distribution" title="Channel sync" description="Status, antrean, dan recovery untuk integrasi OTA." /><UiInlineAlert tone="info">Data sample. Backend belum menyediakan monitoring dan retry channel.</UiInlineAlert><UiInlineAlert v-if="notice" tone="info" live>{{ notice }}</UiInlineAlert><StaffFilterBar :active="activeFilters" :result-label="`${filtered.length} channel`" @apply="() => undefined" @reset="reset"><div class="field"><label for="channel-status">Status</label><select id="channel-status" v-model="status"><option value="">Semua</option><option value="healthy">Healthy</option><option value="delayed">Delayed</option><option value="attention">Attention</option><option value="stale">Stale</option><option value="unknown">Unknown</option></select></div></StaffFilterBar><StaffDataState v-if="!filtered.length && activeFilters.length" no-results @reset="reset" /><div v-else class="ops-grid"><article v-for="channel in filtered" :key="channel.id" class="ops-card" :class="{ 'ops-card--selected': selected?.id === channel.id }"><div class="ops-card__top"><h2>{{ channel.name }}</h2><StaffStatusBadge :label="channel.status" :status="channel.status" /></div><strong>{{ channel.pendingUpdates }} pembaruan menunggu</strong><p>{{ channel.message }}</p><small>Sync terakhir {{ new Date(channel.lastSyncAt).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' }) }}</small><BrandButton @click="selected = channel">Lihat detail</BrandButton></article></div><StaffDetailDrawer id="channel-detail" :open="Boolean(selected) && !review" :title="selected?.name || 'Detail channel'" eyebrow="Channel operation" @close="selected = null"><div v-if="selected" class="stack"><StaffStatusBadge :label="selected.status" :status="selected.status" /><StaffChangeReview :items="[{ label: 'Operation', before: selected.operation, after: selected.lastEvent }, { label: 'Resource', before: selected.resource, after: selected.version }, { label: 'Attempts', before: '0', after: String(selected.attempts) }]" /><UiInlineAlert v-if="selected.sanitizedError" tone="error">{{ selected.sanitizedError }}</UiInlineAlert><BrandButton dark :disabled="!selected.retryEligible" @click="openRetry(selected)">Tinjau retry sample</BrandButton></div></StaffDetailDrawer><StaffActionDialog id="channel-retry" :open="review" title="Konfirmasi retry channel" @close="review = false"><p v-if="selected"><strong>{{ selected.operation }}</strong><br>{{ selected.resource }} · {{ selected.version }}</p><UiInlineAlert tone="error">Retry dapat menduplikasi operasi bila provider sudah menerima attempt sebelumnya. Simulasi ini tidak mengirim payload.</UiInlineAlert><template #actions><BrandButton dark @click="retry">Simulasikan retry</BrandButton><BrandButton @click="review = false">Kembali</BrandButton></template></StaffActionDialog></div></template>
